on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Bump version

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4

        with:
          token: ${{ secrets.CLAP_RELEASE_PLEASE_TOKEN }}
          release-type: simple
